### PR TITLE
Add support for kde & gnome DEs in linux

### LINKED ISSUE #235: add GNU/Linux(GNOME,KDE) proxy settings
program should be able to set proxy setting like windows and mac for linux too.

if you're interested to contribute this feature in Oblivion Desktop please follow this steps:
- make sure no one else is working on this feature and if not coordinate with collaborators before starting to work on this.
- read our Contribution Guide.

this links should be helpful to solve the issue: 

Oblivion Desktop Proxy Lib:
https://github.com/bepass-org/oblivion-desktop/blob/main/src/main/lib/proxy.ts

Implementation of the feature in go lang:
https://github.com/SagerNet/sing-box/blob/84472d3ad2900d9cb3608584ba4522d841ebb38e/common/settings/proxy_linux.go

### PR DESCRIPTION
**Pull request by khodedawsh**
Closes #235

### CODE REVIEW

**Comment by kiomarzsss** [comment]
thank you for your valuable contribution. 🧡
i just formatted the code so it can be easier to review.
im just going to merge it now.
thanks again :))

**Comment by kiomarzsss** [comment]
but there is a one more issue that preventing us from releasing Linux version. and that is currently (even after your PR merged): Ignore Hosts(in gnome), and Exceptions(in kde) are not being set in proxy settings. (this values need to be set with the help of `setRoutingRules`)

**Comment by khodedawsh** [comment]
I'd say your primary concern for linux should be adding tun mode, using badvpn-tun2socks or something similar; since not all applications inherit settings from gsettings/kwrite in linux.
regardless [here](https://wiki.archlinux.org/title/Proxy_server#Proxy_settings_on_GNOME3) is how to ignore the private ranges in gnome.

**Comment by kiomarzsss** [comment]
> I'd say your primary concern for linux should be adding tun mode, using badvpn-tun2socks or something similar + polkit; since not all applications inherit settings from gsettings/kwrite in linux. regardless [here](https://wiki.archlinux.org/title/Proxy_server#Proxy_settings_on_GNOME3) is how to ignore the private ranges in gnome.


i agree with you. till now we tried to re-invent the wheel and that's not a good practice. but the reason we did so was we want it to ship fast. i tried to tun my own system using [sing-box](https://github.com/SagerNet/sing-box) but wasn't able to do it...
i will still try to get the sing-box working with warp-plus cause i think sing-box is the best solution.
if you have any information/guide on how to use sing-box to tunnel all system traffic using a socks outbound(127.0.0.1:8086 by default) that  would very helpful.

**Comment by kiomarzsss** [comment]
در فارسی:

چه فایل کانفیگ‌ای برای sing-box (https://github.com/SagerNet/sing-box) تعریف کنیم که بیاد و از socks proxy ای که warp-plus (به صورت پیشفرض روی 127.0.0.1:8086) استفاده کنه و کل سیستم رو تانل کنه(TUN)؟

**Comment by kiomarzsss** [comment]
خیلی هم عالی. کانفیگش برسه خیلی میتونه کمک کننده باشه. منم هنوز وقت نکردم درست و حسابی بشینم پای sing-box :)
درباره polkit میشه بیشتر توضیح بدی متوجه منظورت نشدم.

**Pull request merged**
