### PR TITLE
Implement Speed Test functionality with Cloudflare SpeedTest

### PR DESCRIPTION
**Pull request by ShadowZagrosDev**
This PR introduces a new Speed Test feature to the application using Cloudflare's SpeedTest package. The implementation includes:

- A new Speed Test page with a user-friendly interface
- Real-time display of download speed, upload speed, latency, and jitter
- Support for starting, pausing, and resuming the speed test
- Responsive design for both light and dark modes
- Localization support for multiple languages

The feature provides users with an easy way to test their connection speed directly within the application, enhancing the overall functionality and user experience.

Screenshots of the new feature at different stages (start, running, and completed) are attached for reference.

I welcome any feedback, suggestions, or questions regarding this implementation. Please don't hesitate to comment if you see any areas for improvement or have any concerns.

speedtest-sc

### CODE REVIEW

**Comment by ircfspace** [comment]
Hello 
thank you for your contribution,

_There are two points that need to be considered:_
1) The ability to repeat the test (which I have set as a TODO in the code)
2) Preventing errors when encountering CORS

image
image

Note: I have made some changes related to the program's user interface.

**Comment by ShadowZagrosDev** [comment]
Here's a concise English response addressing all the points you mentioned:

@ircfspace 
Thank you for your valuable feedback. I've made several improvements to the internet speed test tool:
1. Added a retest functionality as requested.
2. Refactored the code for better optimization, readability, and easier future development.
3. Implemented a Toaster component on the speed test page for in-page notifications, with shorter display times to avoid conflicts with main page messages.

Regarding the error, it was related to Cloudflare's TURN server used for packet loss detection. Since this requires credentials and we don't need packet loss measurement, I've removed it from the default Measurement config. You can view and modify the default settings here: https://github.com/cloudflare/speedtest?tab=readme-ov-file#measurement-config. However, I believe the current values are sufficient.

Please let me know if you have any further questions or suggestions.

**Comment by ShadowZagrosDev** [comment]
@ircfspace 
Thank you for your valuable feedback. I've made several improvements to the internet speed test tool:

1- Added a retest functionality as requested.
2- Refactored the code for better optimization, readability, and easier future development.
3- Implemented a Toaster component on the speed test page for in-page notifications, with shorter display times to avoid conflicts with main page messages.

Regarding the error, it was related to Cloudflare's TURN server used for packet loss detection. Since this requires credentials and we don't need packet loss measurement, I've removed it from the default Measurement config. You can view and modify the default settings here: https://github.com/cloudflare/speedtest?tab=readme-ov-file#measurement-config. However, I believe the current values are sufficient.
Please let me know if you have any further questions or suggestions.

**Comment by ShadowZagrosDev** [comment]
@ircfspace 
Regarding our previous discussion about real-time speed and data usage, I've conducted an experimental implementation and attached a screenshot. As you can see, I've placed the real-time speed on the landing page, but its current location isn't ideal. It conflicts with the IP information display, and adding data usage would make it even more cluttered.
I'd appreciate your thoughts on where and how to best display this information. It's better to decide now to avoid rework later.
Please note that this new feature is unrelated to the current PR. You can merge this PR as is, and I'll submit the new tool in a separate PR later.
sp

**Comment by ircfspace** [comment]
Thank you for your valuable efforts. 
Unfortunately, the testing process still encounters errors at times, leading to issues in the program's execution.

image

**Comment by ShadowZagrosDev** [comment]
@ircfspace 
Thank you for your feedback. It seems the error you encountered was due to a lack of internet connection or inaccessibility to the test server. I've added a 5-second server availability check. If the server is accessible, the test will proceed; otherwise, it won't, and an appropriate message will be displayed. Please test again and let me know if you encounter any errors.

Regarding the real-time speed feature, it's important to note that this test doesn't use internet requests, so we don't need to worry about frequent API calls. It actually measures the user's network speed locally. You can see this on different operating systems using these commands:

For Windows: netstat -e
For macOS: netstat -ib
For Linux: cat /proc/net/dev

If you still want to implement this feature, please let me know, and I'll develop it further.

**Comment by ShadowZagrosDev** [comment]
@ircfspace 
Thank you for the placement and the great styling you've created. The result will look like this:
sp

**Comment by ircfspace** [comment]
I tested the new changes in Speed Test; I observed some errors in the console, but none that would crash the program. However, the problem is that the process does not complete, and despite displaying the download and upload speeds, it remains stuck on loading.

Regarding the display of download and upload speeds, based on the additional explanations you provided, it seems like a good approach. I would appreciate it if you could create a PR for it.

image

**Comment by ShadowZagrosDev** [comment]
@ircfspace 
Regarding the Speed Test, the CORS error usually occurs because the service provider restricts access from localhost. You might notice this error also appears during the ping test on the landing page. Generally, we can ignore these errors (though I must admit, my knowledge of networking is limited).

Could you clarify what you mean by "stuck on loading"? Does the program crash, does the loading animation stop, or do the results just not change? If it’s the last one, it’s likely because the new results are the same as the previous ones, so the UI doesn’t update. Internet quality, speed, and bandwidth can affect these tests, and sometimes there are significant disruptions on Cloudflare. To be sure, you might reduce the number of test measurements in your tests and see if the process completes then.

As for the Realtime-Speed part, the base work is done. However, I want to optimize it to ensure the program doesn’t overuse system resources. It’s also better to finalize the current open PRs to stay focused. But I will definitely create the PR as you suggested. Thanks for your feedback and time.

**Comment by ircfspace** [comment]
Yes, the button with the pause icon remains, and the speed test process does not complete. 
This issue persisted for about 5 minutes until I manually stopped the operation.
If the speed test is complete, it should end, allowing the user to either repeat the operation at their discretion or return to the main page of the application.

Thank you again.
P.S. To expedite coordination, you can contact me at ircfspace@gmail.com.

**Comment by ShadowZagrosDev** [comment]
@ircfspace 
As I mentioned, it depends on the user's connection. For me, it completes in less than a minute with the current configuration. From the screenshot you posted, it seems your upload speed isn't very good. Please test with this configuration for testMeasurements and see if the test completes:

`const testMeasurements = [
    { type: 'latency', numPackets: 1 },
    { type: 'download', bytes: 1e5, count: 1, bypassMinDuration: true },
    { type: 'latency', numPackets: 20 },
    { type: 'download', bytes: 1e5, count: 9 },
    { type: 'upload', bytes: 1e5, count: 8 }
] as const;`

**Comment by ircfspace** [comment]
Unfortunately, the test process still does not complete even after several minutes, and although the download and upload speeds are calculated, it does not finish. 
Additionally, after stopping the operation once and running it again, the program encounters the following error:

**Comment by ircfspace** [comment]
Unfortunately, the test process still does not complete even after several minutes, and although the download and upload speeds are calculated, it does not finish. 
Additionally, after stopping the operation once and running it again, the program encounters the following error:

image

**Comment by ircfspace** [comment]
With a minor adjustment, the issue has now been resolved.

Thank you for your contribution.

**Comment by ShadowZagrosDev** [comment]
@ircfspace 
The number of tests configured in testMeasurements for achieving accurate results is currently low. However, as you mentioned, the main issue now is that even these limited tests are not functioning correctly in the production version, which is quite perplexing.
I've made efforts to identify the root cause of this problem. Through investigation using the network tab in devtools, I've observed that the requests don't seem to be completing properly in the production version. It appears as though they are being restricted in some way.
Unfortunately, despite my attempts, I haven't been able to resolve this issue yet. Given the current situation, I suggest we temporarily remove access to this tool in the drawer until we can find a solution.
I would also like to request that other team members review this issue. Perhaps they can provide insights or assistance in resolving the problem.

**Comment by ircfspace** [comment]
I reverted the testMeasurements values to the state you had configured and rebuilt, but it had no impact on the results. In fact, the Speed Test becomes non-functional after the build. I'm temporarily disabling this feature, but I'd appreciate it if you could create an issue with the "help wanted" label, so others might contribute to resolving the problem.

**Comment by ShadowZagrosDev** [comment]
@ircfspace 
It seems I am unable to create an issue with the "help wanted" label given the repository's issue settings. Could you please create it instead? You can mention that the Speed Test is non-functional in the built version and reference this PR. Additionally, it appears that HTTP requests are not being handled correctly in the built version, as observed through devTools. Thank you in advance!

**Pull request merged**
