### PR TITLE
Add customizable DNS server selection for WARP and GOOL modes

### LINKED ISSUE #409: امکان تغییر dns
### Feature description | توضیحات ویژگی

امکان تغییر dns چون وقتی من connect رو میزنم ارور 1.1.1.1 میده

### PR DESCRIPTION
**Pull request by ShadowZagrosDev**
# DNS Server Selection Feature

This PR adds a DNS server selection option for WARP and GOOL modes.

## Feature Details

- New option in WARP settings tab for DNS server selection
- Sends `--dns` parameter to warp-plus
- Active in WARP and GOOL modes, disabled in Psiphon mode
- Pre-configured DNS servers:
  - Cloudflare (default)
  - Google
  - AdGuard
  - AdGuard Family

## Implementation Notes

- Located in WARP settings tab as it's not effective in Psiphon mode
- Option is disabled and switch is not sent when in Psiphon mode
- Additional DNS servers (OpenDNS, Quad9, Comodo) are commented out for future consideration

## Benefits

- Enhanced user control
- Ad-blocking and content filtering options (AdGuard)
- Parental control capabilities (AdGuard Family)

## Localization

- Translations added for all supported languages in the application

## Screenshot
dns

## Notes for Reviewers

- DNS server list can be easily modified
- Recommend keeping AdGuard options enabled due to their valuable features:
  - AdGuard: Blocks ads and trackers
  - AdGuard Family: Blocks ads, trackers, adult content, and enables Safe Search where possible
- Tested in WARP and GOOL modes

Feedback welcome on DNS server selection, placement in settings, and potential improvements.

Closes #409, #437

### CODE REVIEW

**Comment by ircfspace** [comment]
Hello,

Thank you for your contribution and continued efforts in this matter. 
As you're aware, the DNS flag differs somewhat from the common understanding of DNS. 
According to Mark's explanation, this flag doesn't help improve user connectivity, which is why we didn't include this option in the program. 

However, your PR is well-implemented, and it seems that having it is better than not. 
Given its nature, the option needs to be moved from the Warp settings to the network settings (perhaps somewhere after the blacklist).

Best regards,

**Comment by ShadowZagrosDev** [comment]
@ircfspace 
Thank you for the feedback. Unfortunately, I wasn't aware of Mark's explanations and also this switch's usage. However, as mentioned, I personally tested the feature and observed its effectiveness in GOOL and WARP modes, but not in Psiphon.

My testing process was as follows:
  1. In the default mode (Cloudflare), both advertisements and adult content websites were displayed.
  2. With AdGuard, a significant number of ads were blocked.
  3. AdGuard Family blocked ads and also restricted access to adult content websites.

I conducted these tests across all three modes: WARP, GOOL, and Psiphon. While I tested other DNS servers, they didn't yield notable results. Hence, I kept the AdGuard servers active and commented out the rest. I would appreciate it if you could also verify these findings and test it locally before merging.

Regarding the option's placement, I agree that it should be in the Network tab. However, I placed it in the WARP tab for a specific reason. As my tests showed, the DNS change is effective in WARP and GOOL modes, but not in Psiphon mode. To inform the end-user, this option needs to be disabled when in Psiphon mode. Placing it in the WARP tab allows for easy selection in WARP and GOOL modes and clearly indicates when it's not applicable (in Psiphon mode).

This placement helps users understand in which modes the DNS change is effective and allows for easier DNS switching. Overall, it provides better clarity and usability for the end-user.

If you need any further information or clarification, please let me know.

**Comment by ircfspace** [comment]
Thank you again.

Yes, the current use of the DNS flag is to restrict advertising content or adult content. There's no issue with merging your code; however, as mentioned, it should be placed under the Network tab to ensure proper categorization.

Regarding the UX issue (the switch being under the Psiphon method and the feature being out of sight), we'll try to implement a better solution in future versions, such as displaying a toast notification to inform the user.

If possible, please move the feature to the correct tab and let me know so I can review the PR again.

_There's one more thing:_
 devices that aren't plugged in and are running on battery power are experiencing issues when the program is running (in the new version). It seems that for the previous PR related to displaying data transferred, we need to add an option to make this feature optional (in the same Network tab, after the ipData option, with the default setting as enabled). This would help address the new problem that some users are facing. Could you possibly include this change with the current PR? 
If not, I'll wait until this PR is resolved and then implement the changes myself to avoid conflicts.

Thanks in advance.

**Comment by ShadowZagrosDev** [comment]
@ircfspace 

I've addressed both parts of your feedback:

 1. The DNS selector has been moved to the Network tab for proper categorization.
 2. I've added an option to disable the data transfer display feature, located in the Network tab after the ipData option, with the default setting as enabled. This should help address the battery drain issues some users were experiencing.

Both changes are now included in this PR. Please review when you have a chance. Let me know if you need any further modifications or explanations.

**Comment by ShadowZagrosDev** [comment]
@ircfspace Please don't merge and let me fix the DNS bug

**Comment by ircfspace** [comment]
@ShadowZagrosDev Alright, I'll be waiting for your update

**Comment by ShadowZagrosDev** [comment]
@ircfspace 
Thank you for the changes you made. There was just one issue: when a user hadn't changed the method (for example, after the initial installation of the program) but had changed the DNS server, the --dns switch wasn't being sent. It was necessary for the user to change the method at least once. This problem has now been fixed.

**Comment by ircfspace** [comment]
Thank you for your attention to detail and for the precise changes you made in this PR.

Is it ready to be merged now?

**Comment by ShadowZagrosDev** [comment]
Yes, it is ready to be merged. Thank you for your patience and cooperation.

**Comment by ircfspace** [comment]
Unfortunately, my CPU usage has increased since the recent update. Have you experienced a similar issue? I can't figure out what's causing it!

**Comment by ShadowZagrosDev** [comment]
@ircfspace 
No, I haven't noticed any significant change on my end. Is this happening only when the data usage feature is active and displaying information, or does it occur in both states? If it's only happening when the data usage information is being shown, could you provide more details, such as the percentage increase in CPU usage? This additional information would help me investigate the issue more effectively.

**Comment by ircfspace** [comment]
@ShadowZagrosDev 
Yes, this issue occurs when the data usage feature is active. Interestingly, I built the app once with the previous changes (without the data usage feature) and didn't encounter this problem. However, it seems that displaying the data usage consumes a lot of CPU resources. As soon as it's turned off, CPU usage drops by about 90%.

**Comment by ShadowZagrosDev** [comment]
@ircfspace 
I've attempted to implement some optimizations. Since I didn't personally experience high CPU usage issues, I would greatly appreciate if you could run some tests on the fix-data-usage branch (https://github.com/ShadowZagrosDev/oblivion-desktop/tree/fix-data-usage) and share the results with me. As you can see, I've set the timers to 3 seconds. Please test it with 3 seconds first and observe the outcome. Then, change the timers to 1 second, test again, and let me know the results of both scenarios.
The timers can be found in the startNetworkSpeedMonitoring method in main.ts and the throttledSetSpeeds in useLandings.ts.

**Comment by ircfspace** [comment]
image

I reviewed the changes in the branch and it's strange that it doesn't record any data. 
The CPU usage is at 3% when idle and 30% when active (in the current changes; however, in the previous changes, it was higher, causing the total CPU usage to exceed 90%).

**Comment by ircfspace** [comment]
image

**Comment by ShadowZagrosDev** [comment]
@ircfspace 

Thank you for the additional information.

1. As you can see in the attached screenshot, the information display is working correctly on my system. Given your observation about Windows Security, it seems the issue might be specific to certain Windows configurations.
sc


2. Regarding the 30% CPU usage: Is this consistent for both the 1-second and 3-second timer settings? Logically, if the information calculation is causing such resource consumption, the difference in timer intervals should have a direct impact on resource usage due to their different delays. Could you please clarify if it's the same in both cases? If so, would you mind setting both timers to a larger value, such as 8 seconds?

3. The 15.3% CPU usage shown in the second screenshot - is this during active or inactive data usage display?

4. Regarding the numerous Console Window Hosts: Doesn't this seem unusual? Is it always like this? Were there this many even without this option enabled?

5. Your suggestion to temporarily disable this option seems prudent, given the circumstances. However, before doing so, could you please disable the data sender and instead print the data to the console to check if it works?
I mean from this:
```
if (shouldUpdateStats(lastSentStats, newStats)) {
    if (mainWindow) {
        mainWindow.webContents.send('speed-stats', newStats);
    }
    lastSentStats = newStats;
}
```

to this:
```
if (shouldUpdateStats(lastSentStats, newStats)) {
    //if (mainWindow) {
        //mainWindow.webContents.send('speed-stats', newStats);
    //}
    console.log(newStats);
    lastSentStats = newStats;
}
```

6. The fact that a build from a few days ago is now exhibiting similar behavior is concerning. Could there have been a recent Windows Security update that's affecting this functionality across different versions of the application?

As a non-Windows user, I'm limited in my ability to directly investigate these issues. So I apologize for the added work on your end.

**Comment by ShadowZagrosDev** [comment]
@ircfspace 

I might have found the solution. Please replace and test these two methods (in the fix-data-usage branch) and share the results with me:
```
const startNetworkSpeedMonitoring = () => {
    if (speedMonitorInterval) return;
     if(process.platform === "win32"){
        si.powerShellStart();
    }
    initializeNetworkUsage();
    speedMonitorInterval = setInterval(measureNetworkSpeed, 3000);
};

const stopNetworkSpeedMonitoring = () => {
    if (speedMonitorInterval) {
        clearInterval(speedMonitorInterval);
        speedMonitorInterval = null;
        initialDownloadUsage = 0;
        initialUploadUsage = 0;
        cachedNetworkInterface = null;
        lastSentStats = null;
        if(process.platform === "win32"){
            si.powerShellRelease();
        }
    }
};
```

**Comment by ircfspace** [comment]
@ShadowZagrosDev 
The issue starts when the data retrieval process encounters an error and the process remains open. Despite all the minor changes I've made, a new process runs even though the previous one hasn't completed, which causes the CPU to become heavily engaged after a few seconds. Changing the timeout duration doesn't help in the current situation where the process remains incomplete.

Interestingly, this problem occurred after the Windows update, and another similar Windows system that hasn't been updated yet is working fine (the same version of the program on exactly the same version of Windows, where one has the new update and the other has an older update).

In the other Windows system I mentioned, such a process doesn’t remain open, and the program's CPU usage is limited to a maximum of 1.8 to 3 percent. So, there’s a significant difference in conditions between them.

Unfortunately, changing the Windows security settings hasn't helped solve the issue, and I haven't found a solution yet.

**Comment by ircfspace** [comment]
> @ircfspace
> 
> I might have found the solution. Please replace and test these two methods (in the fix-data-usage branch) and share the results with me:


I'll check this soon and let you know the outcome

**Comment by ircfspace** [comment]
@ShadowZagrosDev 
The current change seems effective for managing CPU usage and can be merged as a PR, but the issue of data exchange not being displayed still persists. I have some ideas I'll try to test out, but it's worth noting that the new version of warp-plus is also coming out soon. It has some changes, and we need to resolve this feature quickly to avoid any confusion.

image

**Comment by ShadowZagrosDev** [comment]
@ircfspace 

I'm glad the CPU usage issue has been resolved. To help us reach a conclusion and merge faster, could you please clarify something for me? With this code, are the statistics not being displayed in the console either?

```
if (shouldUpdateStats(lastSentStats, newStats)) {
    //if (mainWindow) {
        //mainWindow.webContents.send('speed-stats', newStats);
    //}
    console.log(newStats);
    lastSentStats = newStats;
}
```

**Comment by ircfspace** [comment]
To my surprise, nothing is being logged

**Comment by ShadowZagrosDev** [comment]
Okay, I need the fix-data-usage branch in its current state. I'll create a new branch with changes that I think might solve the problem. Once I've made the changes, I'll let you know here so you can test it. If it's okay, I'll create a pull request and we can merge it.

**Comment by ircfspace** [comment]
Following the messages in this PR has become a bit difficult. Please create a new PR after you complete your changes. I won't merge it until we've reached a resolution, but let's continue the discussion there.

**Pull request merged**
