### PR TITLE
Optimize: Reduce CPU usage for Windows speed monitoring

### PR DESCRIPTION
**Pull request by ShadowZagrosDev**
This pull request addresses the high CPU usage issue observed on Windows systems during network speed monitoring. The changes implemented aim to significantly reduce the CPU load while maintaining the functionality of speed monitoring.

### CODE REVIEW

**Comment by ircfspace** [comment]
oblivion desktop, with new changes :
image

without oblivion desktop:
image

**Comment by ShadowZagrosDev** [comment]
Based on what I see in the screenshot, the program is using 18% of CPU. Is that correct?
Please tell me the CPU usage of the program in two states: when displaying data usage and real-time speed statistics, and when not displaying them. Also, do you still have a large number of Console Window Host sub-processes? And are these present in both states?

**Comment by ircfspace** [comment]
image

As shown in the previous screenshot, when OblivionDesktop is running in dataUsage mode, the total CPU usage ranges from 50% to 60%, with the number of sub-processes varying between 8 and 12. As soon as the program is closed, the CPU usage drops below 5%.

On the other hand, when the program is running with dataUsage=off, the number of sub-processes is around 6, and the CPU usage is between 1% and 5%.

**Comment by ShadowZagrosDev** [comment]
Is it possible for you to make some changes manually? Please replace these methods:

```
const initializeNetworkUsage = async () => {
    try {
        if (process.platform === 'win32') {
            si.powerShellStart();
        }
        const networkStats = await si.networkStats();
        const mainInterface = networkStats[0];
        initialDownloadUsage = mainInterface.rx_bytes;
        initialUploadUsage = mainInterface.tx_bytes;
    } catch (error) {
        console.error('Error initializing network speed:', error);
    } finally {
        if (process.platform === 'win32') {
            si.powerShellRelease();
        }
    }
};

const measureNetworkSpeed = async () => {
    try {
        if (process.platform === 'win32') {
            si.powerShellStart();
        }
        const networkStats = await si.networkStats();
        const mainInterface = networkStats[0];

        const currentDownload = mainInterface.rx_sec;
        const currentUpload = mainInterface.tx_sec;
        const totalDownload = mainInterface.rx_bytes - initialDownloadUsage;
        const totalUpload = mainInterface.tx_bytes - initialUploadUsage;
        const totalUsage = totalDownload + totalUpload;

        if (mainWindow) {
            mainWindow.webContents.send('speed-stats', {
                currentDownload,
                currentUpload,
                totalDownload,
                totalUpload,
                totalUsage
            });
        }
    } catch (error) {
        console.error('Error measuring network speed:', error);
    } finally {
        if (process.platform === 'win32') {
            si.powerShellRelease();
        }
    }
};

const startNetworkSpeedMonitoring = () => {
    if (speedMonitorInterval) return;

    initializeNetworkUsage();
    speedMonitorInterval = setInterval(measureNetworkSpeed, 1000);
};

const stopNetworkSpeedMonitoring = () => {
    if (speedMonitorInterval) {
        clearInterval(speedMonitorInterval);
        speedMonitorInterval = null;
        initialDownloadUsage = 0;
        initialUploadUsage = 0;
    }
};
```

**Comment by ircfspace** [comment]
image
image


It didn’t have any effect on the result.

**Comment by ShadowZagrosDev** [comment]
Well, I don't think testing this way can lead us to solve the problem. As I mentioned before, I'm not a Windows user, and for this task, I need to have access to Windows. If you think it's appropriate, let's disable this feature for Windows for now, and as soon as I can get access to Windows, I'll work on fixing this issue. Do you agree?
However, it's necessary to merge this PR because the changes you previously made were causing this tool to malfunction on my system as well. So, if you agree with disabling it for Windows, please let me make the changes in a commit, and then you can merge it.

**Comment by ircfspace** [comment]
Yes, it's fine temporarily

**Comment by ShadowZagrosDev** [comment]
Well, I've disabled it for Windows. You can merge it now. As soon as I fix the issue on Windows, I'll let you know through a new PR.

**Comment by ircfspace** [comment]
Given the issues with systeminformation, it seems that others are also having problems with retrieving network stats on Windows

https://github.com/sebhildebrandt/systeminformation/issues?q=networkStats

**Comment by ShadowZagrosDev** [comment]
Yes, I saw in the issues of the systeminformation package that this problem exists on Windows. However, in the issues, everyone says something different, and I also saw in a PR that a fix for the problem was merged. But we're still facing this issue, considering you said you've updated Windows as well. Now I need to try and see if I can fix the problem or not. By the way, please tell me the Windows version and the update version that caused this problem to occur.

**Comment by ircfspace** [comment]
_Microsoft Windows 10 Home_
OS Version: 10.0.19044 N/A Build 19044
System Type: x64-based PC

_Windows Security:_ 
Last update: yesterday

A similar Windows version that I haven’t updated works correctly with systeminformation, and the oblivionDesktop application has no issues.

**Pull request merged**
