### PR TITLE
Implement GeoIP and GeoSite in TUN Mode (SingBox)

### PR DESCRIPTION
**Pull request by ShadowZagrosDev**
This PR introduces GeoIP and GeoSite functionality to Sing-Box when using TUN mode. A new dropdown has been added to the SingBox settings page, currently offering three options: `None`, `IR (Iran)`, and `CN (China)`. These options allow users to select region-based configurations for Sing-Box.

The selected region is retrieved in `SingBoxManager` from the settings, and the corresponding `geoIp` and `geoSite` values are fetched from the `singBoxGeo` array. These values are then passed to `createSbConfig` to generate the appropriate Sing-Box configuration. If a region other than `None` is selected (i.e., if `geoIp` and `geoSite` are not empty), the necessary settings are applied to customize traffic handling based on the selected region.

This feature is designed to be extendable, allowing the development team to easily add more regions in the future by updating the region options with the necessary GeoIP and GeoSite information.

### CODE REVIEW

**Comment by ShadowZagrosDev** [comment]
I’ve also added GeoBlock, which can be controlled via a checkbox in the SingBox settings page. GeoBlock attempts to block ads, malware, phishing, and crypto miners by utilizing multiple GeoIP and GeoSite sources.

**Note:**
1. The target branch was mistakenly set to `main`. Please change it to `tun`.
2. I'll leave the task of providing appropriate titles and descriptions in different languages to you.

**Comment by ircfspace** [comment]
Hi,
First of all, **thank you for your valuable PR**.

One issue we need to address before finalizing this feature is syncing the current blacklist in the network settings with this new functionality. The current blacklist uses system configuration and is also integrated with PAC settings. The new GEO settings for Sing-Box need to align with those to avoid the user having to enter such configurations separately in multiple steps. 

Do you have any ideas on how we can handle this? Perhaps the new settings could be integrated with the previous ones, or the old settings could be merged with the new ones, eliminating one of them. (Or, when switching to tun mode, the settings the user entered in the previous blacklist could be automatically applied to the new settings). I know my explanation may have caused more confusion! :)

`Also, I emailed you some logs a few days ago—I'd appreciate it if you could take a look at them.`

Thanks again!

**Comment by ircfspace** [comment]
Another point:
Isn't it necessary for the latest updates of GEO files to be hosted on the user's system? (I don't think calling them directly from the URL is a good idea.)

**Comment by ShadowZagrosDev** [comment]
@ircfspace 

Hi,

First of all, thank you so much for your valuable feedback and for sharing your thoughts, as well as the commits you’ve made.

Regarding the first point about syncing the current blacklist with the new Geo settings in Sing-Box, I understand your concern. However, I believe syncing them right now might not be the best approach, as the routing rules we use in Sing-Box are based on regions, whereas the previous blacklist rules are based on domains and IP addresses. Disabling the previous routing rules when switching to TUN mode seems like a simpler solution for now. That said, we might be able to explore better alternatives in the future.

As for your email, I apologize for the delay. I hadn’t checked it over the past few days, but I’ve looked into it now and have sent you a response.

For the second comment, using a local database is indeed possible, but the main challenge is keeping it updated. These databases are regularly updated in their respective repositories, and they may receive multiple updates between our releases. Downloading them periodically via the app isn’t ideal, as the size would likely be larger than the current method. In the current approach, the file size seems to be around 1-2MB (though I haven’t checked the exact size). Also, Sing-Box has caching enabled, which I believe caches these resources, so they aren’t re-downloaded every time the app runs. However, I haven’t checked this in detail either.

As a suggestion, I think we could improve the organization of the SingBox settings page. Since "Stop Operation" and "Stop Helper" relate to the helper, it might be better to place them at the top, while the rest of the settings (related to Sing-Box itself) could go under a section like "More Settings" or "SingBox Settings." Additionally, we could label the two checkboxes related to the helper under a section called "Helper Settings." Separating the helper settings from the Sing-Box settings would make the layout clearer and more intuitive.

Thanks again for your insights!

**Comment by ircfspace** [comment]
Regarding the point you raised about aligning the blacklist with the routing rules, I agree. Since currently the rules are only applied based on location and nothing is manually set, I’m on board with that. However, I was mostly referring to custom rules. What I mean is that, in addition to the location- and IP-based routing rules, which follow a general structure, users should be able to blacklist specific websites or IPs of their choice (similar to what we did with the blacklist option). This would ensure that the blacklist functions correctly in proxy mode, PAC mode, and within Sing-Box.

As for the second point, I probably didn’t review the code properly, and since I’m not at my system right now, it’s a bit difficult for me to check. However, I believe the cache was enabled for the blockingGeo mode, but not for CN/IR. If geoIP/Site is also included in the cache, then there’s no issue for now.

For the third point regarding the order of options in the Sing-Box tab, I think since the "Stop Operation" and "Stop Helper" options are ones that the user might never need to touch or only change once, they are better placed compared to the GEO options.

Of course, these are not final thoughts, and we can discuss them further or rely on user feedback after the release.

Thanks again, and best regards.

**Comment by ShadowZagrosDev** [comment]
@ircfspace 

Thanks for your detailed feedback!

For the first point, I see what you mean now. You’re referring to excluding custom rules (IP, domain) from the singbox so they don’t pass through the tunnel, right? That sounds doable to me—I’ll test it out.

Regarding the second point, although I’m not entirely sure what specifically gets cached, we didn’t restrict caching solely to blockingGeo. We haven’t defined in the config what exactly should or shouldn’t be cached.

As for the third point, the two helper options have stood out more for me, probably because of how frequently I’ve used them during testing. But regardless of whether they’re placed at the top or bottom, I do think it would be better to separate the helper-related settings from the Sing-Box settings.

**Comment by ircfspace** [comment]
For the first point: In version 1, we had the ability to define a list of IPs and domains in the blacklist section so they wouldn’t pass through Warp, such as banking gateways or certain specific domains. Now, when TUN is active, only the routing rules of SingBox (none/ir/cn) work (which is a good thing), but the previously defined blacklist items are no longer applied. It’s necessary for those blacklist items to be applied as well in the app, so the items defined in the blacklist become DIRECT. (Currently, are the rules applied in SingBox via GeoIP/SITE also becoming direct? If they are blocked, I think they should be changed to direct).

Second point, if the file isn’t downloaded every time the app runs and it uses the cache, then that’s fine. Of course, more accurate tests can be done in the future.

Third point, do you mean moving the helper stop feature to the program settings tab? (If yes, I recall that’s what I originally suggested, but after discussing it, we decided to leave it where you put it).

**Comment by ircfspace** [comment]
One more thing: 
For Sing-box, isn't it necessary to consider the 'Other' option in the routing rules settings so that it can load the public geoSite and geoIp files?

For example: 
https://github.com/SagerNet/sing-geosite/releases/tag/20240920063125 
https://github.com/SagerNet/sing-geoip/releases/tag/20240912

**Comment by ShadowZagrosDev** [comment]
@ircfspace 

For the first point, I understand what you mean. I'll test it out when I get the chance and let you know. Since it might take some time, I can’t do it right away. Also, to clarify, no, they’re not blocked. The routing rules based on region are set to DIRECT, while the ones for blocking ads, phishing, etc., are defined as BLOCK.

As for the second point, like I mentioned earlier, I’m not entirely sure what files are cached or whether those resources are downloaded each time the app runs, but that's the whole purpose of caching. If they’re downloaded each time, caching wouldn’t make sense. If you have time, could you please check it yourself?

Regarding the third point, no, I didn’t mean moving the helper settings to a different tab. I was referring to splitting the Sing-Box settings page into two sections—one for helper settings and one for Sing-Box settings.
Something like this:



As for the last comment, I didn’t quite understand your point. Could you explain a bit more?

**Comment by ircfspace** [comment]
For the first point, all good. Thanks.  
For the second point, it’s fine. There shouldn’t be any issues. I’ll check it myself as well.  
For the third point, all good.  
Regarding the fourth point, we currently have 3 options for the routing rules you’ve defined: none, ir, cn. One is for Iran, and the other is for China. However, the app is being used in more countries where internet censorship exists. So, if someone wants to enable this feature and they’re not in Iran or China, there should be a more general option available. That’s why there’s a generic geoIp/geoSite option, which I had sent the link for in a previous message for you to add if possible. In this case, we’ll have 4 options: none, ir, cn, and other.

**Comment by ShadowZagrosDev** [comment]
@ircfspace 

Ah, I see now. I included the rule sets for Iran and China as examples to give the development team a clear approach, and also because I only found sources for those two (I didn’t search for others). To create routing rules for other countries, we’d need the sources for their rule sets. These are available in the geoIp database, but not in geoSite—at least not in the official SagerNet one. That’s why I used "Iran-sing-box-rules" for Iran.

You can download the SagerNet geoIp and geoSite databases, place them next to the Sing-Box executable, and use the following commands (via PowerShell or Command Prompt) to view the list of rule sets:

```
[oblivion-]sing-box.exe [geosite - geoip] list
```

As you’ll see, the list of countries is available for geoIp, but not for geoSite, which has different categories instead. Also, I’m not sure if these two databases are complete and up-to-date for countries other than China.

**Comment by ircfspace** [comment]
I will consult with @hiddify on this matter and add the necessary changes to the code. 
_The changes in this PR have been merged so far._

**Pull request merged**
