### PR TITLE
Introduce Oblivion-Helper for Managing Sing-Box in TUN Mode across Platforms

### PR DESCRIPTION
**Pull request by ShadowZagrosDev**
This PR introduces a new helper, **Oblivion-Helper**, written in Go, to simplify and streamline the management of `sing-box` for TUN mode. The helper is built and released via GitHub Actions (for transparency and code review) and works across macOS, Windows, and Linux platforms. Below are the key features and details:

#### Oblivion-Helper Overview:
- **Admin Privileges**: Oblivion-Helper runs with admin/root privileges and stays in the background, waiting for commands to manage `sing-box`.
- **Input Files**: It uses two input files—one for commands and one for configuration.
- **Monitors (Optional)**: It has two optional monitors that run every 3 seconds:
  - **Warp-Plus Monitor**: This checks if the `warp-plus` process is running. If not, it automatically stops `sing-box` to prevent connection issues caused by an unexpected app closure while the network interface remains altered.
  - **App Process Monitor**: This monitor ensures that if the user exits the app, the helper shuts down as well. It’s optional, as keeping it disabled allows the helper to persist in the background, avoiding repeated admin prompts on future app launches.
- **Log File**: All messages and events are logged in `oblivion-helper.log` for easier troubleshooting.
- **Cross-Platform Compatibility**: The helper is built and released for all supported platforms and architectures (macOS, Windows, Linux).

The helper significantly simplifies `sing-box` management by reducing the need for repeated admin prompts and optimizing resource usage. The full source code is available in the GitHub repository for review, and I'd appreciate any feedback from those with expertise, especially on improving security or functionality. https://github.com/ShadowZagrosDev/oblivion-helper

#### SingBoxManager Integration:
- Oblivion-Helper is downloaded from GitHub and integrated directly into the `SingBoxManager` for seamless management across platforms.
- The manager uses the helper to control `sing-box`, sending necessary commands via input files and configuring the monitor options (whether to enable or disable them).
- A dynamic `sing-box` configuration file is generated, allowing parameters like `port` and `mtu` to be set based on the user's needs. I've included a sample to demonstrate how to use it, but the development team can extend it as needed.

#### Sing-Box Settings Page:
- A new settings page for `sing-box` is accessible via the drawer. This page currently includes:
  - Two checkboxes to toggle the helper’s monitors (for Warp-Plus and app process monitoring).
  - A modal for adjusting the `mtu` setting.
  
  The development team can expand this page to include more configurable options for `sing-box`, and the UI/UX can be further refined as needed.

#### Testing:
- I've tested this implementation on macOS and Windows, and it works smoothly, establishing the necessary connections.
- On Linux, the helper and `sing-box` run correctly, but the final connection wasn't established due to configuration issues. It would be helpful if someone with deeper knowledge of `sing-box` configurations could review this.

In summary, using Oblivion-Helper makes managing `sing-box` much more efficient and resource-friendly. I look forward to any feedback or suggestions for improvement.

### CODE REVIEW

**Comment by ircfspace** [comment]
Thank you for your contribution.
I will review the situation and provide an update.

Two points:
1) Is it possible to move the Singbox settings to the network settings tab?
2) How long is the oblivion-helper.log file retained, and are there any conditions for it to be automatically deleted or reset under specific circumstances or within a certain time period?

**Comment by ShadowZagrosDev** [comment]
@ircfspace 

Yes, it’s definitely possible, and the decisions regarding UI/UX are up to you. My personal preference, though, is to keep all the settings related to sing-box in one place rather than spreading them across different sections for easier and more intuitive access. I added the MTU setting mainly as an example to show how it can be passed for configuration generation. As you know, sing-box configurations offer many optional/adjustable settings that users can customize. In the future, we also plan to take advantage of other features like geoip, which can also be customized by users. Keeping all these settings in a dedicated page avoids user confusion or mistakes. For example, the MTU setting is only relevant in the TUN (sing-box) mode, and if it’s not separated, users might mistakenly think it applies to other modes as well. With that said, I prefer to keep all sing-box settings on a dedicated page. For testing purposes, I placed access to this page in the drawer, but that can change. For example, there could be a button in the Network Settings tab that links to this dedicated page. The decision is yours.

As for the log file, it gets overwritten every time the helper starts. So, each time the helper runs, the logs are written anew. I don’t think auto-deleting the log when the helper closes is a good idea because the helper might crash or encounter an issue, and the log file helps the user troubleshoot. After all, that’s the point of logging. May I ask under what specific conditions or time frame you’re thinking about auto-deletion? In my opinion, the current setup works fine, as the logs get reset at each new helper start.

P.S. I emailed you last night from Tw*50, did you see it?

**Comment by ircfspace** [comment]
Thank you for all the effort you've put in so far. Unfortunately, the issue of tun0 not being created still persists for me.

The first time, it connected correctly and tun0 was created in the network by Singbox. However, after the connection (even though I opened Twitter and everything was fine), I got a Singbox stop error in a toast notification. Since then, every time I hit connect, it connects, but it gets stuck in the 'receiving data' state, and tun0 hasn’t been added.

This issue isn’t from my internet, because without any significant changes to my internet or endpoint, I can connect using the system proxy.

image
image
image

**Comment by ShadowZagrosDev** [comment]
@ircfspace 

Thank you so much for your valuable feedback and the additional commits you’ve made. I really appreciate your participation.

It’s strange that the issue with the tun interface not being created still occurs on the first run across different methods we've tried with Sing-box. I’m starting to think the problem might be related to your local environment. Could you possibly test it on a different machine or at least under a different user account on the same system?

Also, could you check the contents of the helper log file and share any relevant details?

In terms of establishing the connection, when we call the `checkConnectionStatus` method, we’re not doing anything specific with Sing-box at that point. We simply fetch the same address used in the `getIpLocation` (which retrieves location data) to check if that address is accessible. With this Sing-box configuration, it seems to take a few seconds for the connection to become fully available and usable. That’s why I’ve placed the helper and Sing-box startup process at the beginning of the connection flow, and we only check the connection once it is successfully established (indicated by the success message).

For testing on your end, you could try bypassing this step temporarily by adding `return true;` at the start of the `checkConnectionStatus` method. After launching the helper and Sing-box, wait a few seconds to see if the connection becomes available.

**Comment by ircfspace** [comment]
@ShadowZagrosDev  Thank you,
the changes have been merged.

I'll build it now to run more tests.

I also asked @kiomarzsss to run the necessary tests on Linux if possible.
I hope he can allocate time for this.

**Comment by kiomarzsss** [comment]
hi @ShadowZagrosDev . i hope you're doing well.
 i couldn't find a better place to share this.

i tested the 'tun' branch/feature on linux(debian)
while it seems it's working properly(it creates tun0 network interface)
but i encountered the following problems:
- app can't disconnect and also asks for sudo password for connect and disconnect every time.

also it's been a long time that wp won't work on my ISP. so i couldn't really test it :)
hope it helps.
and good luck.
:raised_back_of_hand:

**Pull request merged**
