### PR TITLE
Optimize network speed monitoring and re-enable for Windows

### PR DESCRIPTION
**Pull request by ShadowZagrosDev**
This pull request includes significant improvements to the network speed monitoring functionality, with a focus on optimizing performance for Windows systems.

Key changes:
  1. Refactored and optimized the network speed monitoring code
  2. Re-enabled speed and data usage statistics display for Windows
  3. Improved overall efficiency and reliability across all platforms

While I cannot guarantee perfect functionality on Windows (as I don't have direct access to test), I've made my best effort to address the previously reported issues. The changes should provide a more stable and efficient experience for all users, including those on Windows systems.
I kindly request thorough testing on Windows systems to verify the effectiveness of these changes. Any feedback or further suggestions for improvement are welcome.

### CODE REVIEW

**Comment by ShadowZagrosDev** [comment]
@ircfspace

Could you please review and test this PR? It seems that the CPU usage situation has improved.

I'd also like to suggest that when a user enables this option, we display a message via Toaster (similar to settingsHaveChangedToast) with the following content: "If this option causes high system resource usage, please turn it off."

I think we should keep this option enabled for Windows and allow users to test it and decide for themselves whether to keep it on or off. Due to the variety of Windows versions and different updates people might have installed, the high resource usage isn't consistent and could vary from system to system.

**Comment by ShadowZagrosDev** [comment]
There are existing code segments that require refactoring to optimize performance, improve functionality, and enhance readability. As an example, I've refactored the cfFlag function in the commit above. Would you like me to continue this refactoring process gradually as I find time and opportunity?

**Comment by ircfspace** [comment]
Thank you.

1. I will start reviewing the PR now and will let you know the results.
2. Yes, your contribution to improving this program, which ultimately serves as a bridge for public access to the internet, is valuable to everyone.

**Comment by ircfspace** [comment]
View of resource status with the dataUsage option turned **on** :
image

View of resource status with the dataUsage option turned **off** :
image

View of the program output:
image

**Comment by ShadowZagrosDev** [comment]
Regarding development, absolutely. I'll collaborate with you towards this goal as much as I can.
About the statistics display issue you encountered, thank you for your feedback. I tested the app on a friend's mid-range laptop with Windows 11 and the latest updates. The stats were displayed correctly, and CPU usage was below 10%. Following our previous discussions, I think there might be an issue specific to your system. Perhaps Windows Defender has become sensitive to the app and is preventing PowerShell commands from executing. Your screenshot shows high anti-malware usage, suggesting it might be interfering with the app and its commands.
Could you try building the app and see if the issue persists with the built version? Is it possible for you to test on another system? Can you completely disable Windows Defender and check the results? Could you ask other team members to test as well?
Regardless of each system's hardware capabilities, the variety of Windows versions and different updates each user might have received makes this problem more complex and challenging to track and resolve.

**Comment by ircfspace** [comment]
As I mentioned before, this issue does not occur on another Windows system that hasn't been updated. However, I am still working on finding a workaround for Windows Defender, but I haven't been successful so far

**Comment by ircfspace** [comment]
It seems that keeping this PR open to find a solution, which is uncertain in terms of when we might achieve it, would be unproductive. I will go ahead and merge the recent changes.

**Comment by ShadowZagrosDev** [comment]
How about the suggestion I made in this [comment](https://github.com/bepass-org/oblivion-desktop/pull/461#issuecomment-2267352750) regarding a message similar to settingsHaveChangedToast for this option?

**Comment by ircfspace** [comment]
@ShadowZagrosDev 
That's a good idea.
please just wait a bit while we integrate the new version of Warp-Plus with the app and upgrade to the latest version.

Thank you in advance.

**Pull request merged**
