### PR TITLE
Add total data usage breakdown and optimize code

### PR DESCRIPTION
**Pull request by ShadowZagrosDev**
This PR implements the following changes:

1. Add display of total data transferred during the connection session
2. Include breakdown of total upload and download stats
3. Optimize the existing code

Notes:
- Temporarily using 'speed', 'upload', and 'download' classes for styling to position information appropriately. Final styling adjustments can be made as needed.
- The current implementation of showing total upload and download as a tooltip may not be ideal:
  a) It requires focus on the application window
  b) The tooltip closes and reopens on each value change
  Please feel free to adjust this display method for better user experience.

All requested features from the previous PR comments have now been implemented.

dt

### CODE REVIEW

**Comment by ShadowZagrosDev** [comment]
It seems there's an issue with `src/renderer/components/Modal/Restore/index.tsx` at line 26:25 that's preventing commits from being pushed. Please check it out.

**Comment by ircfspace** [comment]
Thank you for your valuable contribution.

The changes related to the user interface have been implemented.

However, there is an issue: if we switch between different tabs in the application for any reason, the total usage statistics on the main page get reset. This should only happen when we connect or disconnect.

**Comment by ShadowZagrosDev** [comment]
@ircfspace 
Thank you for your feedback and also the UI changes. The result is indeed very satisfactory.
Regarding the issue of usage statistics resetting when switching between tabs, let's examine this code snippet:
`ipcRenderer.sendMessage('check-speed', isConnected && ipData);`
This code optimizes calculations to occur only when the connection is active and the IP information display is enabled. However, since ipData is reset and re-fetched each time we return to the main tab (which is evident in the IP information display section as we can see the IP information being fetched every time we return to the main page), it causes a momentary pause and restart in calculations, leading to the reset of usage data.
I've modified the condition as follows:
`ipcRenderer.sendMessage('check-speed', isConnected && proxyStatus !== 'none');`
I removed ipData to prevent resets when returning to the main tab. This allows calculations to continue even when IP information display is disabled. While it would be ideal to calculate only when IP display is active, this change has the advantage of preventing usage data calculations from resetting when a user disables IP information display via settings while connected. Additionally, the proxyStatus !== 'none' condition ensures calculations only occur when necessary, improving efficiency.
Please review these changes and let me know if you need any further clarification or modifications.

**Comment by ircfspace** [comment]
Thank you again,
It seems the process is now correct.

The changes have been merged.

**Comment by ShadowZagrosDev** [comment]
@ircfspace 
You're welcome. I'm glad the process is now correct.

Regarding a new feature proposal: As you know, warp-plus has a DNS switch defaulting to 1.1.1.1, which we don't currently push in the Oblivion Desktop. I've noticed requests for DNS change options in the issues, and I believe it could be a useful addition, especially for blocking ads, trackers, adult content, phishing attempts, etc.

Would you agree to implement this feature? Here are my thoughts and suggestions:

1. The switch seems effective in warp and gool modes but not in psiphon mode based on my tests.

2. If we want to add this option to settings, I recommend placing it in the warp settings tab. It could function similar to the country option for psiphon - disabled when in psiphon mode (using default DNS) but active and changeable in other modes (warp, gool).

3. We could source DNS addresses from within the app or make them receivable from GitHub, similar to endpoints. My suggestion is to start with in-app options.

4. Besides Cloudflare's DNS, we could add others like Google, AdGuard (regular and family-safe versions). We could also include an option for users to manually enter their preferred DNS.

What are your thoughts on these suggestions? If you agree, I'd appreciate your feedback on each point mentioned. Thank you!

**Pull request merged**
